apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: subnet-public-1a
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1a
    cidrBlock: 172.32.1.0/24
    vpcIdRef:
      name: development
    mapPublicIPOnLaunch: true
    tags:
    - key: Environment
      value: development
    - key: Owner
      value: SRE
    - key: Name
      value: subnet-public-1a
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: subnet-private-1a
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1a
    cidrBlock: 172.32.2.0/24
    vpcIdRef:
      name: development
    mapPublicIPOnLaunch: true
    tags:
    - key: Environment
      value: Live
    - key: Owner
      value: SRE
    - key: Name
      value: subnet-private-1a
  providerConfigRef:
    name: default
